apiVersion: v1
kind: ServiceAccount
metadata:
  name: carrier-installer
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carrier-installer
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - watch
  - patch

- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch

- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - delete
  - list
  - update
  - patch
  - watch

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - list
  - update
  - patch
  - watch
  - delete

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - create
  - get
  - update
  - delete
  - list
  - patch
  - watch


- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - delete

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - create
  - patch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - create

- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - update
  - patch
  - watch

- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - create
  - delete
  - list
  - update
  - patch
  - watch

- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - delete
  - patch

- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
  - list
  - get
  - delete
  - watch

- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - approve
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update

- apiGroups:
  - "quarks.cloudfoundry.org"
  resources:
  - quarkssecrets
  verbs:
  - get
  - list
  - update
  - watch
  - delete
  - create

- apiGroups:
  - "quarks.cloudfoundry.org"
  resources:
  - quarkssecrets/status
  verbs:
  - update

- apiGroups:
  - "certificates.k8s.io"
  resources:
  - signers
  resourceNames:
  - "kubernetes.io/legacy-unknown"
  verbs:
  - approve

- apiGroups:
  - ""
  resources:
  - ingresses
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch

- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - create
  - delete

- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch

- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - list
  - delete
  - create
  - update
  - patch
  - watch

- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - webhook.pipeline.tekton.dev
  verbs:
  - get
  - update

- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - delete

- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - config.webhook.pipeline.tekton.dev
  verbs:
  - get
  - update

- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - validation.webhook.pipeline.tekton.dev
  verbs:
  - get
  - update

- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - delete

- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - create
  - delete

- apiGroups:
  - "policy"
  resources:
  - podsecuritypolicies
  resourceNames:
  - tekton-pipelines
  verbs:
  - use
  - get

- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - create
  - delete

- apiGroups:
  - "policy"
  resources:
  - podsecuritypolicies
  verbs:
  - create
  - patch

- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - "tekton.dev"
  resources:
  - clustertasks
  - clustertasks/status
  - conditions
  - pipelineresources
  - pipelineresources/status
  - pipelineruns
  - pipelineruns/finalizers
  - pipelineruns/status
  - pipelines
  - pipelines/status
  - runs
  - runs/finalizers
  - runs/status
  - taskruns
  - taskruns/finalizers
  - taskruns/status
  - tasks
  - tasks/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch

- apiGroups:
  - "tekton.dev"
  resources:
  - conditions
  - pipelineresources
  - pipelineruns
  - pipelines
  - taskruns
  - tasks
  verbs:
  - deletecollection

- apiGroups:
  - "triggers.tekton.dev"
  resources:
  - clustertriggerbindings
  - eventlisteners
  - triggerbindings
  - triggers
  - triggertemplates
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carrier-installer
roleRef:
  kind: ClusterRole
  name: carrier-installer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: carrier-installer
  namespace: "{{ .Release.Namespace }}"
