kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: drone-runner-kube-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: drone
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

