---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: drone
  namespace: drone
spec:
  rules:
    - host: drone.{{PUBLIC_IP}}.nip.io
      http:
        paths:
          - backend:
              serviceName: drone
              servicePort: 80
            path: /
