apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: staging-triggertemplate
  namespace: eirini-workloads
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: staging-pipeline-run-$(uid)
        namespace: eirini-workloads
      spec:
        serviceAccountName: staging-triggers-admin
        pipelineRef:
          name: staging-pipeline
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(tt.params.gitrevision)
              - name: url
                value: $(tt.params.gitrepositoryurl)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: staging-pipelinebinding
  namespace: eirini-workloads
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: eirini-workloads
    - name: gitrepositoryurl
      value: "http://gitea.gitea:10080/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: staging-listener
  namespace: eirini-workloads
spec:
  serviceAccountName: staging-triggers-admin
  triggers:
    - bindings:
      - ref: staging-pipelinebinding
      template:
        ref: staging-triggertemplate
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-pipeline
  namespace: eirini-workloads
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
    - name: stage
      taskRef:
        name: stage
      resources:
        inputs:
        - name: source-repo
          resource: source-repo
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stage
  namespace: eirini-workloads
spec:
  resources:
    inputs:
    - name: source-repo
      type: git
      targetPath: app
  steps:
    - name: stage
      image: lachlanevenson/k8s-kubectl
      workingDir: "/workspace/app"
      command:
        - sh
      args:
        - -c
        - |
          ls -la
          kubectl apply -f ./.kube/*
