---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  namespace: gitea
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: gitea
data:
  app.ini: |
    APP_NAME = carrier
    RUN_MODE = prod
    [server]
    DOMAIN = gitea.{{PUBLIC_IP}}.nip.io
    ROOT_URL  = http://gitea.{{PUBLIC_IP}}.nip.io/
    [repository]
    ROOT = /data/git/gitea-repositories
    [database]
    DB_TYPE = sqlite3
    PATH = /data/gitea/gitea.db
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = generated-by-quarks-secret
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MDIzNzc3NzZ9.uvJPCMSDTPlVMAUwNzW9Jbl5487kbj5T_pWu3dGirnA
    [service]
    ENABLE_REGISTRATION_CAPTCHA = false
    DISABLE_REGISTRATION = true
    [openid]
    ENABLE_OPENID_SIGNIN = false
    [oauth2]
    ENABLE = true
    JWT_SECRET = HLNn92qqtznZSMkD_TzR_XFVdiZ5E87oaus6pyH7tiI
---
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
        istio-injection: enabled
        version: v1
    spec:
      initContainers:
      - name: migrate
        image: gitea/gitea:1.12.5
        command:
        - sh
        - -c
        - /usr/bin/entrypoint /app/gitea/gitea migrate
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini 
      - name: create-admin
        image: gitea/gitea:1.12.5
        command:
        - sh
        - -c
        - /usr/bin/entrypoint /app/gitea/gitea admin create-user --username dev --password changeme --email admin@carrier.sh --admin || true
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini 
      containers:
      - name: gitea
        image: gitea/gitea:1.12.5
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini
      volumes:
      - name: gitea-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-pv-claim
      - name: config-volume
        configMap:
          name: config

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-svc
  namespace: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - name: ssh
    protocol: TCP
    port: 10022
    targetPort: 22
    nodePort: 30022
  - name: http
    protocol: TCP
    port: 10080
    targetPort: 3000
    nodePort: 30080

