---
apiVersion: v1
kind: Pod
metadata:
  name: carrier-copier
  namespace: carrier
spec:
  volumes:
    - name: carrier-binary
      persistentVolumeClaim:
        claimName: carrier-binary
  containers:
    - name: copier
      image: busybox
      command: ["/bin/sh", "-ec", "while :; do printf '.'; sleep 5 ; done"]
      volumeMounts:
        - mountPath: "/carrier"
          name: carrier-binary
