---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: carrier
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: carrier-server
    app.kubernetes.io/part-of: carrier
    app.kubernetes.io/version: 0.0.0 # TODO: {{ version }}
  name: carrier-server
  namespace: carrier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: carrier-server
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: carrier-server
      app.kubernetes.io/part-of: carrier
  template:
    metadata:
      labels:
        app.kubernetes.io/component: carrier-server
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: carrier-server
        app.kubernetes.io/part-of: carrier
        app.kubernetes.io/version: 0.0.0 # TODO: {{ version }}
      name: carrier-server
    spec:
      volumes:
        - name: carrier-binary
          persistentVolumeClaim:
            claimName: carrier-binary
      containers:
        - command: ["/carrier/carrier", "server"]
          args: ["--port", "8080"]
          # TODO: Create a base image
          #image: carrier/base:{{ version }}
          image: jimmykarily/carrier-baseimage
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          name: carrier-server
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
          volumeMounts:
            - mountPath: "/carrier"
              name: carrier-binary
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 65532
      # TODO Create an appropriate server account: serviceAccountName: cluster-admin
