---
apiVersion: batch/v1
kind: Job
metadata:
  name: linkerd-uninstall
  namespace: linkerd
spec:
  template:
    spec:
      serviceAccountName: linkerd-installer
      containers:
      - name: linkerd-uninstall
        image: splatform/epinio-linkerd:2.10.2
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: 
          - linkerd uninstall --verbose | kubectl delete -f -
      restartPolicy: Never
  backoffLimit: 1
