---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
data:
  app.ini: |
    APP_NAME = carrier
    RUN_MODE = prod
    [server]
    DOMAIN = {{ .Values.domain | trimSuffix "/" }}
    ROOT_URL  = http://{{ .Values.domain | trimSuffix "/" }}/
    [repository]
    ROOT = /data/git/gitea-repositories
    [database]
    DB_TYPE = sqlite3
    PATH = /data/gitea/gitea.db
    [security]
    INSTALL_LOCK = true
    SECRET_KEY = generated-by-quarks-secret
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MDIzNzc3NzZ9.uvJPCMSDTPlVMAUwNzW9Jbl5487kbj5T_pWu3dGirnA
    [service]
    ENABLE_REGISTRATION_CAPTCHA = false
    DISABLE_REGISTRATION = true
    [openid]
    ENABLE_OPENID_SIGNIN = false
    [oauth2]
    ENABLE = true
    JWT_SECRET = HLNn92qqtznZSMkD_TzR_XFVdiZ5E87oaus6pyH7tiI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gitea.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: migrate
        image: {{ .Values.image }}
        command:
        - sh
        - -c
        - /usr/bin/entrypoint /app/gitea/gitea migrate
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini 
      - name: create-admin
        image: {{ .Values.image }}
        command:
        - sh
        - -c
        - /usr/bin/entrypoint /app/gitea/gitea admin create-user --username dev --password changeme --email admin@carrier.sh --admin || true
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini 
      containers:
      - name: gitea
        image: {{ .Values.image }}
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /data
        - name: config-volume
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini
      volumes:
      - name: gitea-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-pv-claim
      - name: config-volume
        configMap:
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
  ports:
  - name: ssh
    protocol: TCP
    port: 10022
    targetPort: ssh
    nodePort: 30022
  - name: http
    protocol: TCP
    port: 10080
    targetPort: http
    nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.domain | trimSuffix "/" | quote }}
    http:
      paths:
      - backend:
          service:
            name: gitea
            port:
              number: 10080
        path: /
        pathType: ImplementationSpecific
