---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: brigade
  namespace: brigade
spec:
  rules:
    - host: "brigade.{{PUBLIC_IP}}.nip.io"
      http:
        paths:
          - backend:
              serviceName: brigade-server-kashti
              servicePort: 80
            path: /
