name: Test for self hosted runner

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Test
      run: make test
